# Generated by Django 6.0.3 on 2026-03-30 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "monthly_salary",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "monthly_expenses",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("total_savings", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "risk_tolerance",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=15)),
                ("area_sqft", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "bhk",
                    models.IntegerField(
                        choices=[
                            (1, "1 BHK"),
                            (2, "2 BHK"),
                            (3, "3 BHK"),
                            (4, "4 BHK"),
                            (5, "5+ BHK"),
                        ]
                    ),
                ),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("villa", "Villa"),
                            ("plot", "Plot"),
                            ("commercial", "Commercial"),
                        ],
                        default="apartment",
                        max_length=20,
                    ),
                ),
                (
                    "age_years",
                    models.IntegerField(
                        default=0, help_text="Age of property in years"
                    ),
                ),
                ("floor_number", models.IntegerField(default=1)),
                ("total_floors", models.IntegerField(default=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvestmentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "predicted_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "predicted_rental",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("down_payment", models.DecimalField(decimal_places=2, max_digits=15)),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("loan_tenure_years", models.IntegerField(default=20)),
                (
                    "interest_rate",
                    models.DecimalField(decimal_places=2, default=8.5, max_digits=5),
                ),
                (
                    "emi",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total_interest",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "affordability_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "roi_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=7, null=True
                    ),
                ),
                (
                    "investment_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "recommendation",
                    models.CharField(
                        blank=True,
                        choices=[("BUY", "Buy"), ("HOLD", "Hold"), ("AVOID", "Avoid")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "projected_value_5yr",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analyses",
                        to="realestate.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
